version: '3.4'

x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      BUNDLER_VERSION: '<bundler-version>'
  image: <application-name>-dev
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  environment: &backend-env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
    REDIS_URL: redis://redis:6379/
    REDIS_HOST: redis
    REDIS_POST: 6379
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    SELENIUM_URL: http://selenium:4444/wd/hub
    TEST_APP_HOST: 'http://test'
    TEST_APP_PORT: 8200
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: minio
    AWS_SECRET_ACCESS_KEY: 2NVQWHvTT73XMgqapGchy6yAtwHezMZn
    S3_BUCKET: <application-name>-development
    S3_FORCE_PATH: 'true'
    S3_ENDPOINT: http://172.17.0.1:9000

    # Misc
    BOOTSNAP_CACHE_DIR: /bundle/bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    EDITOR: vi
  volumes:
    - ../:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - ./.psqlrc:/root/.psqlrc:ro
    - ./.pryrc:/root/.pryrc:ro
  depends_on:
    - postgres
    - redis
    - minio
    - selenium

services:
  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000

  runner:
    <<: *backend
    command: /bin/bash
    environment:
      <<: *backend-env
      HOST: http://rails:3000
      DOMAIN: http://localhost:3000

  jobs:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      <<: *backend-env
      HOST: http://rails:3000

  webpacker:
    <<: *app
    stdin_open: true
    tty: true
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - ..:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      RAILS_ENV: ${RAILS_ENV:-development}
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  postgres:
    image: postgres:<postgres-version>
    volumes:
      - ./.psqlrc:/root/.psqlrc:ro
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: <application-name>_development
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432

  redis:
    image: redis:<redis-version>-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

  minio:
    image: minio/minio
    volumes:
      - ./volumes/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 2NVQWHvTT73XMgqapGchy6yAtwHezMZn
    ports:
      - 9000:9000
    command: server /data

  minio-client:
    image: minio/mc
    command: /bin/sh
    entrypoint: /bin/sh
    volumes:
      - ./scripts:/scripts:ro
    depends_on:
      - minio

  # Useful to not depend on your computer chrome version
  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    volumes:
      - ..:/app:cached
    ports:
      - 5900:5900
      - 4444

volumes:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
