version: '3.4'

services:
  postgres:
    image: postgres:<postgres-version>
    volumes:
      - ./.psqlrc:/root/.psqlrc:ro
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432

  redis:
    image: redis:<redis-version>-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

  minio:
    image: minio/minio
    volumes:
      - ./volumes/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 2NVQWHvTT73XMgqapGchy6yAtwHezMZn
    ports:
      - 9000:9000
    command: server /data

  minio-client:
    image: minio/mc
    command: /bin/sh
    entrypoint: /bin/sh
    volumes:
      - ./scripts:/scripts:ro
    depends_on:
      - minio

volumes:
  redis:
